<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bde9024e-3d28-4cf8-80ae-5c88ee777cd6</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_category_phone</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/footer[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.page-footer-menu__element[href='\/category\/phone']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'page-footer-menu__element is-link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-footer-menu__element is-link</value>
        <webElementGuid>5dac9b77-195d-4e9e-b536-ad80f5190c03</webElementGuid>
    </webElementProperties>
</WebElementEntity>