<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>abfe5379-acb4-4686-8a04-93ef34e754de</elementGuidId>
    <imagePath></imagePath>
    <name>ul_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/ul[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.products</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'products list-unstyled page-block')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>products list-unstyled page-block</value>
        <webElementGuid>25cbd47e-4c49-43d5-9c48-9f96101523ff</webElementGuid>
    </webElementProperties>
</WebElementEntity>