<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d1bd3dfd-21c1-4adc-b83c-6f507874a402</elementGuidId>
    <imagePath></imagePath>
    <name>input_receive_marketing_info</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.bdl-contact-form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'receive_marketing_info') and equals(@class,'PrivateSwitchBase-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input css-1m9pwf3</value>
        <webElementGuid>47f69211-7018-4d80-b9ff-8b4a255049eb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>receive_marketing_info</value>
        <webElementGuid>f18c34be-3acd-4a56-bd5b-8d6b015b6c03</webElementGuid>
    </webElementProperties>
</WebElementEntity>