<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bc5f9820-7aa1-4e6e-bfdb-c66028c53022</elementGuidId>
    <imagePath></imagePath>
    <name>input_billing_address_state</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[4]/div[1]/div[6]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:rf\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':rf:') and equals(@name,'billing_address.state') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>e49fefc3-4a2d-4314-b343-a303f9ee6967</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:rf:</value>
        <webElementGuid>f82ed826-c108-461f-a22b-860634567662</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>billing_address.state</value>
        <webElementGuid>f59af454-673e-4ae2-b24e-19dd55ee078e</webElementGuid>
    </webElementProperties>
</WebElementEntity>