<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d6bbe020-0c46-443a-af27-2457bb588054</elementGuidId>
    <imagePath></imagePath>
    <name>input_shipping_address_first_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r2\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':r2:') and equals(@name,'shipping_address.first_name') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>c1093cd2-d890-45fd-86e5-2644c28f12b1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:r2:</value>
        <webElementGuid>7978aa89-36ab-43a5-9551-f04f926113b0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>shipping_address.first_name</value>
        <webElementGuid>38c6b9a5-8ef5-4e8c-8ef4-5edb1fca0ea6</webElementGuid>
    </webElementProperties>
</WebElementEntity>