<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>108cf962-db52-4d78-8069-28215b6c41e5</elementGuidId>
    <imagePath></imagePath>
    <name>input_shipping_address_address_line_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[3]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r4\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':r4:') and equals(@name,'shipping_address.address_line_1') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>860060be-f72c-4d65-b3bc-89efcb2a9ca7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:r4:</value>
        <webElementGuid>a2f73c61-441f-4f8f-9262-bbd441c3d0da</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>shipping_address.address_line_1</value>
        <webElementGuid>3b0ef219-9a57-4585-8f9c-d1f0bb009d62</webElementGuid>
    </webElementProperties>
</WebElementEntity>