<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dc3d5a1d-a255-491b-b326-6992c7f8f230</elementGuidId>
    <imagePath></imagePath>
    <name>input_delivery_id</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/fieldset[1]/div[1]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.bdl-shipping-form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'delivery_id') and equals(@class,'PrivateSwitchBase-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input css-1m9pwf3</value>
        <webElementGuid>7fca9ccb-62e1-4d13-bd5e-56069e944c4b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>delivery_id</value>
        <webElementGuid>f980151c-4f90-4147-8dcd-e7a394d1285b</webElementGuid>
    </webElementProperties>
</WebElementEntity>