<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e111b980-c42f-49a1-8e99-57cf301ed462</elementGuidId>
    <imagePath></imagePath>
    <name>h1_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/h1[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.page-heading</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'page-heading page-heading_h1 page-heading_m-h1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-heading page-heading_h1 page-heading_m-h1</value>
        <webElementGuid>4d682201-c0ff-4c29-9bbd-b487f96d42e4</webElementGuid>
    </webElementProperties>
</WebElementEntity>