<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2226f6bb-b52d-469d-b3c5-6773fdd1d9b8</elementGuidId>
    <imagePath></imagePath>
    <name>ul_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/ul[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.products</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'products list-unstyled page-block')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>products list-unstyled page-block</value>
        <webElementGuid>ad3fd9c2-ea69-4c34-8e6f-0a615b0a987e</webElementGuid>
    </webElementProperties>
</WebElementEntity>