<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e5854c4a-5722-46de-84c6-60fb9799a0ca</elementGuidId>
    <imagePath></imagePath>
    <name>ul_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/ul[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.products</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'products list-unstyled page-block')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>products list-unstyled page-block</value>
        <webElementGuid>2bc0de78-30aa-4724-be7c-9fea255a5df7</webElementGuid>
    </webElementProperties>
</WebElementEntity>